game_characters = {	{name = 'Reimu Hakurei A', stats = {name = 'Player', char = '@', evasion = 0, team = 0, x = 24, y = 14, speed = 9, hp_max = 500, mana_max = 200, base_damage = {45, 55}},
					player_stats = { str = 6, dex = 9, int = 5, con = 7 },
					starting_spells = {	game_spells[1], game_spells[2],  },
					player_spells_learn = { {spell = game_spells[3], level = 3}, {spell = game_spells[4], level = 5},
											{spell = game_spells[10], level = 6},
											},
					},
					{name = 'Reimu Hakurei B', stats = {name = 'Player', char = '@', evasion = 0, team = 0, x = 24, y = 14, speed = 8, hp_max = 400, mana_max = 300, base_damage = {40, 50}},
					player_stats = { str = 4, dex = 8, int = 10, con = 5 },
					starting_spells = { game_spells[5], game_spells[7], },
					player_spells_learn = { {spell = game_spells[8], level = 3}, {spell = game_spells[9], level = 5}	},
					},
					{name = 'Reimu Hakurei C', stats = {name = 'Player', char = '@', evasion = 0, team = 0, x = 24, y = 14, speed = 8, hp_max = 450, mana_max = 250, base_damage = {48, 52}},
					player_stats = { str = 5, dex = 8, int = 7, con = 6 },
					starting_spells = { game_spells[11], game_spells[6], game_spells[12], },
					player_spells_learn = { {spell = game_spells[13], level = 3} },
					},
					{name = 'Reimu Hakurei D', stats = {name = 'Player', char = '@', evasion = 5, team = 0, x = 24, y = 14, speed = 8, hp_max = 425, mana_max = 250, base_damage = {50, 60}},
					player_stats = { str = 6, dex = 8, int = 5, con = 6 },
					starting_spells = { game_spells[14], },
					player_spells_learn = { {spell = game_spells[15], level = 2}, {spell = game_spells[16], level = 4}, },
					},					
				}
				