game_quests = {	{	name = 'Find My Glasses', 
					desc = 'I\'ve lost my glasses while in a dungeon north of your shrine.  Will you please find and return them to me?',
					completed_text = 'Thank you for finding my glasses.  Here, take this magical mirror as a reward.',
					npc = 'Human Elder',
					npc_location = 'Human Village',
					type = 'fetch', 
					item = 'Glasses', 
					reward = 'Magic Mirror',
					have = false,
					completed = false,
					},
				{	name = 'Exterminate Shizuha Aki',
					desc = 'Shizuha Aki living deep in the youkai forest has been infected by the Jaaku and must be exterminated.',
					completed_text = 'You\'ve made the forest safer for travelers, now take this special gohei for your reward.',
					npc = 'Kanako Yasaka',
					npc_location = 'Moriya Shrine',
					type = 'kill',
					target = 'Shizuha Aki',
					reward = 'Purification Rod',
					have = false,
					completed = false,
					},
				}