game_mutations = {	{name = 'Claws', power = 5, message = "Your hands grow into sharp claws."},
					{name = 'Enhanced Vision', sight = 2, message = "Your vision becomes more refined."},
					{name = 'Tengu Legs', speed = 1, message = "Your legs begin to vibrate rapidly."},
					{name = 'Raw Hide', armor = 2, message = "Your skins hardens."},
					{name = 'Half Ghost', no_feet = 1, message = "Your feet merge into a wispy tail."},
					{name = 'Hunger', hunger = 10, message = "Your stomach vibrates and begins to howl."},
					{name = 'Small Arms', power = -5, message = "Your arms shrink back into your body."},
					{name = 'Delicate Wings', fly = 1, armor = -5, message = "You sprout large, silky wings from your back."},
					{name = 'Body Spikes', no_torso = 1, armor = 5, thorns = .25, message = "You grow large spikes all over your chest and back."},
					{name = 'Snail Metabolism', hunger = -10, speed = -2, message = "Your metabolism and speed begin to match those of a snail."},
					{name = 'Slow Thinking', manaregen = -10, evasion = -2, message = "You can't think as fast when on your feet."},
					{name = 'Slow Healer', hpregen = -10, message = "Your body's natural healing mechanics feel slower now."},
					}